include:
  - project: 'warmichi/templates'
    file: '/terraform.gitlab-ci.yml'

.secrets:
  secrets:
    HCLOUD_TOKEN:
      vault: infra/prod/hetzner/HCLOUD_TOKEN@secret
      file: false
    HCLOUD_SSH_RANCHER_PRIVATE_KEY:
      vault: infra/prod/hetzner/HCLOUD_SSH_RANCHER_PRIVATE_KEY@secret
      file: false
    HCLOUD_SSH_RANCHER_PUBLIC_KEY:
      vault: infra/prod/hetzner/HCLOUD_SSH_RANCHER_PUBLIC_KEY@secret
      file: false