include:
  - project: 'warmichi/templates'
    file: '/terraform.gitlab-ci.yml'

variables:
  BOOTSTRAP_KUBE_CLUSTER:
    value: "false"
    description: "decide if the cluster should be bootstrapped."
  SCALE_KUBE_CLUSTER:
    value: "false"
    description: "scale nodes in the cluster."
  UPGRADE_KUBE_CLUSTER:
    value: "false"
    description: "Gracefully upgrade the cluster to the given version "

.secrets:
  secrets:
    HCLOUD_TOKEN:
      vault: infra/prod/hetzner/HCLOUD_TOKEN@secret
      file: false
    HETZNER_DNS_API_TOKEN:
      vault: infra/prod/hetzner/HETZNER_DNS_API_TOKEN@secret
      file: false 
    TF_VAR_hcloud_ssh_root_private_key:
      vault: infra/prod/hetzner/HCLOUD_SSH_ROOT_PRIVATE_KEY@secret
    TF_VAR_hcloud_ssh_root_public_key:
      vault: infra/prod/hetzner/HCLOUD_SSH_ROOT_PUBLIC_KEY@secret
      file: false
    TF_VAR_hcloud_ssh_warmichi_private_key:
      vault: infra/prod/hetzner/HCLOUD_SSH_WARMICHI_PRIVATE_KEY@secret
    TF_VAR_hcloud_ssh_warmichi_public_key:
      vault: infra/prod/hetzner/HCLOUD_SSH_WARMICHI_PUBLIC_KEY@secret
      file: false

.gitlab-tf-backend: &gitlab-tf-backend
  - export TF_ADDRESS=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/production
  - export TF_HTTP_ADDRESS=${TF_ADDRESS}
  - export TF_HTTP_LOCK_ADDRESS=${TF_ADDRESS}/lock
  - export TF_HTTP_LOCK_METHOD=POST
  - export TF_HTTP_UNLOCK_ADDRESS=${TF_ADDRESS}/lock
  - export TF_HTTP_UNLOCK_METHOD=DELETE
  - export TF_HTTP_USERNAME=gitlab-ci-token
  - export TF_HTTP_PASSWORD=${CI_JOB_TOKEN}
  - export TF_HTTP_RETRY_WAIT_MIN=5
  - echo "Using HTTP Backend at $TF_HTTP_ADDRESS"
  - terraform --version
  - terraform init -reconfigure

apply:
  stage: apply
  script:
    - *gitlab-tf-backend
    - chmod 600 $TF_VAR_hcloud_ssh_root_private_key
    - terraform apply -auto-approve
    - DYNAMIC_ENVIRONMENT_URL=$(terraform output -no-color env_dynamic_url)
    - echo "DYNAMIC_ENVIRONMENT_URL=$DYNAMIC_ENVIRONMENT_URL" >> deploy.env
  artifacts:
    paths:
      - inventory
  inherit:
    variables: [
      BOOTSTRAP_KUBE_CLUSTER, 
      SCALE_KUBE_CLUSTER, 
      UPGRADE_KUBE_CLUSTER
      ]
  cache:
    key: ansible_inventory_cache
    paths:
      - inventory
  when: manual
