include:
  - project: 'warmichi/templates'
    file: '/terraform.gitlab-ci.yml'

.secrets:
  secrets:
    HCLOUD_TOKEN:
      vault: infra/prod/hetzner/HCLOUD_TOKEN@secret
      file: false
    HETZNER_DNS_API_TOKEN:
      vault: infra/prod/hetzner/HETZNER_DNS_API_TOKEN@secret
      file: false 
    TF_VAR_HCLOUD_SSH_ROOT_PRIVATE_KEY:
      vault: infra/prod/hetzner/HCLOUD_SSH_ROOT_PRIVATE_KEY@secret
    TF_VAR_HCLOUD_SSH_ROOT_PUBLIC_KEY:
      vault: infra/prod/hetzner/HCLOUD_SSH_ROOT_PUBLIC_KEY@secret
      file: false
    TF_VAR_HCLOUD_SSH_WARMICHI_PRIVATE_KEY:
      vault: infra/prod/hetzner/HCLOUD_SSH_WARMICHI_PRIVATE_KEY@secret
    TF_VAR_HCLOUD_SSH_WARMICHI_PUBLIC_KEY:
      vault: infra/prod/hetzner/HCLOUD_SSH_WARMICHI_PUBLIC_KEY@secret
      file: false
    TF_VAR_RANCHER_UI_PASSWORD:
      vault: infra/prod/hetzner/RANCHER_UI_PASSWORD@secret
      file: false
    TF_VAR_RANCHER_TOKEN_KEY:
      vault: infra/prod/hetzner/RANCHER_TOKEN_KEY@secret
      file: false
