#cloud-config
runcmd:
- export INSTALL_RANCHERD_VERSION=v2.5.9
- apt-get update
- curl -sfL https://get.rancher.io | sh -
- systemctl enable rancherd-server.service
- systemctl start rancherd-server.service
- export KUBECONFIG=/etc/rancher/rke2/rke2.yaml PATH=$PATH:/var/lib/rancher/rke2/bin