#cloud-config

# install rancher using ranherd
runcmd:
- apt-get update
- curl -sfL https://get.rancher.io | INSTALL_RANCHERD_VERSION=v2.5.9 sh -
- systemctl enable rancherd-server.service --now
- rancherd --token RANCHER_TOKEN_KEY

# set persistent enviroment variables
write_files:
- path: /root/.profile
  content: |
    export KUBECONFIG=/etc/rancher/rke2/rke2.yaml PATH=$PATH:/var/lib/rancher/rke2/bin
  append: true
- path: /etc/rancher/rke2/config.yaml
  content: |
    token: 00a52523acfd20eb6363b73a87b777712cc7bbfd4d443e21fb82ce8dcda624c0
  append: true
