---
- hosts: rancher
  become: yes
  gather_facts: no
  tasks:
  - name: Update repositories cache
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: download rancherd installation script
    get_url:
      url: https://get.rancher.io
      dest: /tmp/rancherd_install.sh
      mode: 0755

  - name: Execute the rancherd_install.sh
    shell: /tmp/rancherd_install.sh
    notify:
    - systemd enable and start rancherd-server

  handlers:
  - name: systemd enable and start rancherd-server
    ansible.builtin.systemd:
      daemon_reload: yes
      name: rancherd-server
      enabled: yes
      state: started