---
- hosts: rancher
  become: yes
  gather_facts: no
  tasks:
  - name: Update repositories cache
    apt:
      update_cache: yes

  - name: download rancherd installation script
    get_url:
      url: https://get.rancher.io
      dest: /tmp/rancherd_install.sh

  - name: Execute the rancherd_install.sh
    shell: /tmp/rancherd_install.sh
    notify:
    - start rancherd-server

  handlers:
  - name: start rancherd-server
    service:
      name: rancherd-server
      enabled: yes
      state: started
  