name: "Terraform Apply"

on:
  push:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: "warmichi"
  TF_WORKSPACE: "hetzner"
  CONFIG_DIRECTORY: "./"

jobs:
  vault:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.mycompany.com:8200
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            prod/hetzner/HETZNER_DNS_API_TOKEN;
            prod/hetzner/HCLOUD_TOKEN;
            prod/hetzner/HCLOUD_SSH_ROOT_PRIVATE_KEY;
            prod/hetzner/HCLOUD_SSH_ROOT_PUBLIC_KEY;
            prod/hetzner/HCLOUD_SSH_WARMICHI_PUBLIC_KEY;
            prod/hetzner/HCLOUD_SSH_WARMICHI_PUBLIC_KEY;
            prod/argocd/ARGOCD_VAULT_TOKEN;
            prod/hetzner/TF_API_TOKEN;
  terraform:
    if: github.repository != 'hashicorp-education/learn-terraform-github-actions'
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: apply-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: apply-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

      - name: Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"
