name: Vault Secrets

on:
  workflow_call:

jobs:
  vault:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.mycompany.com:8200
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            prod/hetzner/HETZNER_DNS_API_TOKEN;
            prod/hetzner/HCLOUD_TOKEN;
            prod/hetzner/HCLOUD_SSH_ROOT_PRIVATE_KEY;
            prod/hetzner/HCLOUD_SSH_ROOT_PUBLIC_KEY;
            prod/hetzner/HCLOUD_SSH_WARMICHI_PUBLIC_KEY;
            prod/hetzner/HCLOUD_SSH_WARMICHI_PUBLIC_KEY;
            prod/argocd/ARGOCD_VAULT_TOKEN;
            prod/hetzner/TF_API_TOKEN;
